---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: '1.13'
  name: clickhouse

- src: git@github.com:DeluxWebSite/vector-role.git
  scm: git
  version: 'v1.1'
  name: vector-role

- src: git@github.com:DeluxWebSite/lighthouse-role.git
  scm: git
  version: '1.1'
  name: lighthouse-role
